PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS Rents;
DROP TABLE IF EXISTS Books;
DROP TABLE IF EXISTS Authors;
DROP TABLE IF EXISTS Customers;

CREATE TABLE Authors (
    ID INTEGER PRIMARY KEY,
    Name TEXT NOT NULL
);

CREATE TABLE Books (
    ID INTEGER PRIMARY KEY,
    Name TEXT NOT NULL,
    Author INTEGER,
    FOREIGN KEY (Author) REFERENCES Authors(ID)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

CREATE TABLE Customers (
    ID INTEGER PRIMARY KEY,
    Name TEXT NOT NULL,
    Email TEXT NOT NULL UNIQUE
);

CREATE TABLE Rents (
    ID INTEGER PRIMARY KEY,
    BookID INTEGER NOT NULL,
    CustomerID INTEGER NOT NULL,
    State TEXT NOT NULL CHECK (State IN ('Returned','On time','Overdue')),
    FOREIGN KEY (BookID) REFERENCES Books(ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (CustomerID) REFERENCES Customers(ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
